# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - snowflakegenai

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip the App folder for deployment
        run: zip -r python-app.zip App/
        # Asegúrate de que el directorio 'App/' contiene todo tu código y archivos necesarios.

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app-zip  # El nombre del artefacto que se va a cargar. 
          path: python-app.zip  # La ruta del archivo que se va a cargar.

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app-zip  # Asegúrate de que esto coincida con el nombre del artefacto que subiste

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'snowflakegenai'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7C2AA6C3E4314B59BBA33BF8B837D8BD }}
          package: python-app.zip  # La ruta local al archivo ZIP descargado.